# Generated by Django 6.0.6 on 2026-06-14 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='notes_pdfs/'),
        ),
    ]
